// <auto-generated />
using Blackjack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blackjack.Migrations
{
    [DbContext(typeof(BlackjackDbContext))]
    partial class BlackjackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blackjack.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"));

                    b.Property<string>("LobbyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player1ID")
                        .HasColumnType("int");

                    b.Property<int>("Player2ID")
                        .HasColumnType("int");

                    b.Property<int>("StartHP")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("int");

                    b.HasKey("GameID");

                    b.HasIndex("Player1ID");

                    b.HasIndex("Player2ID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Blackjack.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Blackjack.Models.PlayerHand", b =>
                {
                    b.Property<int>("PlayerHandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerHandID"));

                    b.Property<string>("DrawnCardsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HandValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<int>("RoundID")
                        .HasColumnType("int");

                    b.HasKey("PlayerHandID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("RoundID");

                    b.ToTable("PlayerHands");
                });

            modelBuilder.Entity("Blackjack.Models.Round", b =>
                {
                    b.Property<int>("RoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoundID"));

                    b.Property<int>("DamageDealt")
                        .HasColumnType("int");

                    b.Property<byte[]>("Deck")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<int>("LoserPlayerID")
                        .HasColumnType("int");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.HasKey("RoundID");

                    b.HasIndex("GameID");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Blackjack.Models.Game", b =>
                {
                    b.HasOne("Blackjack.Models.Player", "Player1")
                        .WithMany("GamesAsPlayer1")
                        .HasForeignKey("Player1ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blackjack.Models.Player", "Player2")
                        .WithMany("GamesAsPlayer2")
                        .HasForeignKey("Player2ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("Blackjack.Models.PlayerHand", b =>
                {
                    b.HasOne("Blackjack.Models.Player", "Player")
                        .WithMany("PlayerHands")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blackjack.Models.Round", "Round")
                        .WithMany("PlayerHands")
                        .HasForeignKey("RoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Blackjack.Models.Round", b =>
                {
                    b.HasOne("Blackjack.Models.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Blackjack.Models.Game", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Blackjack.Models.Player", b =>
                {
                    b.Navigation("GamesAsPlayer1");

                    b.Navigation("GamesAsPlayer2");

                    b.Navigation("PlayerHands");
                });

            modelBuilder.Entity("Blackjack.Models.Round", b =>
                {
                    b.Navigation("PlayerHands");
                });
#pragma warning restore 612, 618
        }
    }
}
